title: MY FUTURE PLAN
author: GitHub User
email: yuliana81santi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I would like to share about my previous background and what I currently am doing. 
 A lot of things had happened in the past few years of my life. 

# social links
twitter_username: Yuliana Santi
github_username:  yuliana81santi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
